language: python

python:
  - "3.5"

# command to install dependencies
install:
  - pip install -r requirements.txt

before_script:
# command for creating a role and a database
  - psql -c "CREATE ROLE oriaso WITH SUPERUSER LOGIN PASSWORD 'root100';" -U postgres
  - psql -c 'CREATE DATABASE ride_my_way;' -U postgres
  - psql -c 'ALTER DATABASE ride_my_way OWNER TO oriaso;' -U postgres

# command to run tests
script: coverage run -m pytest

# command to run test coverage
after_success:
  - coveralls

# command to start postgresql
services:
  - postgresql